### ISSUE TITLE
Unable to connect with Interface

### ISSUE THREAD

**Issue by pavan-cs** [rudrakshpathak/laravel-service-repository-pattern#1]
`[2018-05-19 16:33:52] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to App\Services\User\UserService::__construct() must be an instance of App\Repositories\User\UserInterface, instance of Illuminate\Foundation\Application given, called in D:\workspace\test\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php on line 208 in D:\workspace\test\app\Services\User\UserService.php:19`

**Comment by rudrakshpathak** [comment]
This has been resolved
